### ISSUE TITLE
Ícones SVG

### ISSUE THREAD

**Issue by danielnass** [bubbstore/ecommerce-icons#3]
Olá a todos!

Notei que os ícones SVG estão com um tamanho, algo em torno de ~800kb, o que foge de um dos propósitos do formato.

Alguém tem os fontes dos ícones e exporta-los novamente?

Agradeço desde já!

**Comment by lucascolette** [comment]
@danielnass obrigado pela observação! Ícones otimizados 👍

**Comment by danielnass** [comment]
@lucascolette obrigado!
